apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kgky794tl-go 
  janus-idp.io/tekton: kgky794tl-go
  backstage.io/kubernetes-id: kgky794tl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kgky794tl-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml