apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kgky794tl-go-gitops
  description: This is GitOps manifest for kgky794tl-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=kgky794tl-go
    backstage.io/kubernetes-id: kgky794tl-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: kgky794tl-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kgky794tl-go
