apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kgky794tl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kgky794tl-go 
  name: kgky794tl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kgky794tl-go 
